export const SOCKET_EVENT = {
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  SEND_MESSAGE: "send_message",
  RECEIVE_MESSAGE_CONVERSATION: "receive_message_conversation",
  RECEIVE_MESSAGE_USER: "receive_message_user",
  ERROR: "error",
  ADD_NEW_CONVERSATION: "add_new_conversation",
  JOIN_CONVERSATION: "join_conversation",
  LEAVE_CONVERSATION: "leave_conversation",
  UPDATE_CONVERSATION: "update_conversation",
  ONLINE: "online",
  OFFLINE: "offline",
  SOCKET_NAVIGATION: "socket_navigation",
};
